### ISSUE TITLE
Ambiguous methods introduced in v3.7.0

### ISSUE THREAD

**Issue by BenGoldberg** [recurly/recurly-client-dotnet#536]
We updated our library to v3.7.0 today and noticed all of the method calls on the Recurly client now are ambiguous. For example:

```
var request = new AccountCreate
{
    Code = accountCode,
    Email = email,
    FirstName = firstName,
    LastName = lastName,
    Company = company
};

if (!String.IsNullOrEmpty(billingToken))
{
    request.BillingInfo = new BillingInfoCreate
    {
        TokenId = billingToken
    };
}

await ExecuteAsync(() => _client.CreateAccountAsync(request));
```

The call to `_client.CreateAccountAsync()` is now ambiguous. We had to add `options: null` to all of the client calls to fix the issue. This isn't a huge deal but since this was just introduced, I was wondering if this was intended behavior? Is it possible to make the methods not require the RequestOptions again, or is this how it has to be?

**Comment by bhelx** [comment]
I don't think this was intended to be a breaking change. Will have @douglasmiller take a look.

**Comment by douglasmiller** [comment]
@BenGoldberg thank you for your patience with this issue. As @bhelx pointed out, this was not intended to be a breaking change. I've removed the overloaded async methods, which were intended to be a convenience to developers and, instead, turned out to be an inconvenience 👎 

We are aware of the lack of sufficient testing around the async methods and operations in the library and are working on adding more testing around this area.

**Comment by BenGoldberg** [comment]
No big inconvenience here, thank you for quickly addressing this issue! We will be looking out for the upcoming release.

**Comment by douglasmiller** [comment]
@BenGoldberg the 3.7.1 release has been [published to nuget](https://www.nuget.org/packages/Recurly/3.7.1). Thanks again for creating these issues. It helps us out a lot!
